language: python
python:
  - "2.7"
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
install:
  - pip install -r requirements.txt
script:
  - 'nosetests --with-xunit --cover-xml'
  - DB_URL=postgresql://postgres@localhost/postgres nosetests -a functional
after_script:
  - 'pip install scrutinizer-ocular'
  - ocular
sudo: false
cache: pip
