language: python
python:
  - "2.7"
services:
  - postgresql
before_script:
  - psql -U postgres -c "create extension postgis"
install:
  - 'python setup.py develop'
script:
  - 'nosetests --with-xunit --cover-xml'
  - DB_URL=postgresql://postgres@localhost/postgres nosetests -a functional
after_script:
  - 'pip install scrutinizer-ocular'
  - ocular
sudo: false
cache: pip
